##version: '3.8'
#
#services:
#  postgres:
#    container_name: postgres_container
#    image: postgres
#    environment:
#      POSTGRES_USER: adarshdm
#      POSTGRES_PASSWORD: adarshdm  # Corrected typo in password variable name
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - 5432:5432
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: False
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - 5050:80
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - 5672:5672  # RabbitMQ default port
#      - 15672:15672  # RabbitMQ management UI port
#    networks:
#      - microservice-network
#      - postgres
#
#
#  zipkin:
#    container_name: zipkin
#    image: openzipkin/zipkin
#    ports:
#      - 9411:9411
#    networks:
#      - microservice-network
#      - postgres
#
#  config-server:
#    image: adarshdm/config-server:latest
#    container_name: config-server
#    ports:
#      - 8080:8080
#    depends_on:
#      - servicereg
#    networks:
#      - microservice-network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#
#
#  servicereg:
#    image: adarshdm/servicereg:latest
#    container_name: servicereg
#    ports:
#      - 8761:8761
#    depends_on:
#      - rabbitmq
#      - zipkin
#      - postgres
#      - pgadmin
#    networks:
#      - microservice-network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#
#
#  companyms:
#    image: adarshdm/companyms:latest
#    container_name: companyms
#    ports:
#      - 8081:8081
#    depends_on:
#      - servicereg
#      - config-server
#    networks:
#      - microservice-network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#
#
#  jobms:
#    image: adarshdm/jobms:latest
#    container_name: jobms
#    ports:
#      - 8082:8082
#    depends_on:
#      - servicereg
#      - config-server
#    networks:
#      - microservice-network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka
#
#
#  reviewms:
#    image: adarshdm/reviewms:latest
#    container_name: reviewms
#    ports:
#      - 8083:8083
#    depends_on:
#      - servicereg
#    networks:
#      - microservice-network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#
#
#  gateway:
#    image: adarshdm/gateway:latest
#    container_name: gateway
#    ports:
#      - 8084:8084
#    depends_on:
#      - servicereg
#    networks:
#      - microservice-network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#
#
#
#networks:
#  microservice-network:
#    driver: bridge
#  postgres:
#    driver: bridge
#
#volumes:
#  postgres:
#  pgadmin:



version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: adarshdm
      POSTGRES_PASSWORD: adarshdm  # Corrected typo in password variable name
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672 # RabbitMQ default port
      - 15672:15672 # RabbitMQ management UI port
    networks:
      - postgres
    environment:
#      RABBITMQ_DEFAULT_USER: "admin"  # RabbitMQ default username
#      RABBITMQ_DEFAULT_PASS: "password"  # RabbitMQ default password
      RABBITMQ_DEFAULT_USER: "a"
      RABBITMQ_DEFAULT_PASS: "a"



networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
